name: build + publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
      - name: Deploy on shadcn-svelte to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://uulauu.de
          app: 'shadcn-svelte'
          token: '${{ secrets.SHADCN_SVELTE_APP_TOKEN }}'
          image: 'ghcr.io/matissdk/shadcn-svelte:latest'